---
language: generic

os:
  - linux
  - osx

env:
  global:
    - PACKAGE_NAME=zeroc-ice
    - PATH="$HOME/miniconda/bin:$PATH"

install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - conda install -y conda-build anaconda-client

script:
  - conda build .

deploy:
  provider: script
  skip_cleanup: true
  script: anaconda -t $CONDA_UPLOAD_TOKEN upload -u $CONDA_USER -l nightly $HOME/miniconda/conda-bld/$TRAVIS_OS_NAME-64/$PACKAGE_NAME-*.tar.bz2 --force
  on:
    branch: master

# Based on
# https://gist.github.com/zshaheen/fe76d1507839ed6fbfbccef6b9c13ed9/22cc5a53c3d3532be5605b4a9751d042a7db6bfe
